/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import couseassignment.chat.ChatClient;
import couseassignment.chat.ChatResponse;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author priva_000
 */
public class Application extends javax.swing.JFrame implements Observer {

    private final ChatClient client;
    private final String DEFAULT_MESSAGE = "Write your message here";

    /**
     * Creates new form Application
     */
    public Application(ChatClient client) {
        initComponents();
        this.client = client;

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    client.close();
                } catch (IOException ex) {
                    Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
                }

                super.windowClosing(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewSwitcher = new javax.swing.JPanel();
        authenticateWindow = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        btnAuthenticate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chatWindow = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        userListScrollPane = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();
        chatPanel = new javax.swing.JPanel();
        chatMessagesScrollPane = new javax.swing.JScrollPane();
        chatMessagesPanel = new javax.swing.JPanel();
        chatMessagesItemsPanel = new javax.swing.JPanel();
        chatFormPanel = new javax.swing.JPanel();
        messageScrollPane = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        buttonContainerPanel = new javax.swing.JPanel();
        btnSendMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChatProject");
        setBackground(new java.awt.Color(251, 251, 251));

        viewSwitcher.setLayout(new java.awt.CardLayout());

        btnAuthenticate.setText("Connect");
        btnAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthenticateActionPerformed(evt);
            }
        });

        jLabel1.setText("Write your username");

        javax.swing.GroupLayout authenticateWindowLayout = new javax.swing.GroupLayout(authenticateWindow);
        authenticateWindow.setLayout(authenticateWindowLayout);
        authenticateWindowLayout.setHorizontalGroup(
            authenticateWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticateWindowLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(authenticateWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(authenticateWindowLayout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAuthenticate)))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        authenticateWindowLayout.setVerticalGroup(
            authenticateWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticateWindowLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authenticateWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAuthenticate)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        viewSwitcher.add(authenticateWindow, "authenticate");

        chatWindow.setLayout(new javax.swing.BoxLayout(chatWindow, javax.swing.BoxLayout.LINE_AXIS));

        sidebarPanel.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        sidebarPanel.setMinimumSize(new java.awt.Dimension(250, 27));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(250, 558));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        userListScrollPane.setBorder(null);

        userList.setBackground(new java.awt.Color(102, 102, 102));
        userList.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        userList.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        userList.setForeground(new java.awt.Color(255, 255, 255));
        userList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Everyone" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        userList.setFocusable(false);
        userList.setName(""); // NOI18N
        userList.setSelectedIndex(0);
        userListScrollPane.setViewportView(userList);

        sidebarPanel.add(userListScrollPane, java.awt.BorderLayout.CENTER);

        chatWindow.add(sidebarPanel);

        chatPanel.setMinimumSize(new java.awt.Dimension(400, 27));
        chatPanel.setLayout(new javax.swing.BoxLayout(chatPanel, javax.swing.BoxLayout.PAGE_AXIS));

        chatMessagesScrollPane.setBorder(null);
        chatMessagesScrollPane.setAutoscrolls(true);

        chatMessagesPanel.setBackground(new java.awt.Color(235, 242, 255));
        chatMessagesPanel.setAutoscrolls(true);
        chatMessagesPanel.setOpaque(false);
        chatMessagesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        chatMessagesItemsPanel.setLayout(new javax.swing.BoxLayout(chatMessagesItemsPanel, javax.swing.BoxLayout.PAGE_AXIS));
        chatMessagesPanel.add(chatMessagesItemsPanel);

        chatMessagesScrollPane.setViewportView(chatMessagesPanel);

        chatPanel.add(chatMessagesScrollPane);

        chatFormPanel.setBackground(new java.awt.Color(204, 204, 204));
        chatFormPanel.setMaximumSize(new java.awt.Dimension(32846, 150));
        chatFormPanel.setLayout(new javax.swing.BoxLayout(chatFormPanel, javax.swing.BoxLayout.LINE_AXIS));

        messageScrollPane.setBorder(null);
        messageScrollPane.setOpaque(false);
        messageScrollPane.setPreferredSize(new java.awt.Dimension(246, 50));

        txtMessage.setColumns(20);
        txtMessage.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txtMessage.setLineWrap(true);
        txtMessage.setRows(1);
        txtMessage.setTabSize(0);
        txtMessage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMessageFocusLost(evt);
            }
        });
        txtMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMessageMouseClicked(evt);
            }
        });
        txtMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMessageKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMessageKeyReleased(evt);
            }
        });
        messageScrollPane.setViewportView(txtMessage);

        chatFormPanel.add(messageScrollPane);

        buttonContainerPanel.setMaximumSize(new java.awt.Dimension(240, 150));
        buttonContainerPanel.setMinimumSize(new java.awt.Dimension(240, 0));
        buttonContainerPanel.setName(""); // NOI18N
        buttonContainerPanel.setOpaque(false);
        buttonContainerPanel.setPreferredSize(new java.awt.Dimension(100, 0));
        buttonContainerPanel.setLayout(new java.awt.BorderLayout());

        btnSendMessage.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        btnSendMessage.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnSendMessage.setText("Send");
        btnSendMessage.setBorder(null);
        btnSendMessage.setContentAreaFilled(false);
        btnSendMessage.setMaximumSize(new java.awt.Dimension(40, 25));
        btnSendMessage.setMinimumSize(new java.awt.Dimension(40, 25));
        btnSendMessage.setPreferredSize(new java.awt.Dimension(40, 25));
        btnSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMessageActionPerformed(evt);
            }
        });
        buttonContainerPanel.add(btnSendMessage, java.awt.BorderLayout.CENTER);

        chatFormPanel.add(buttonContainerPanel);

        chatPanel.add(chatFormPanel);

        chatWindow.add(chatPanel);

        viewSwitcher.add(chatWindow, "chat");

        getContentPane().add(viewSwitcher, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthenticateActionPerformed
        String username = txtUsername.getText();
        if (username.equals("")) {
            return;
        }

        this.client.send("USER#" + username);

        CardLayout cardLayout = (CardLayout) viewSwitcher.getLayout();
        cardLayout.show(viewSwitcher, "chat");
        

        resetTextMessage();
    }//GEN-LAST:event_btnAuthenticateActionPerformed

    private void btnSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMessageActionPerformed
        sendMessage();
    }//GEN-LAST:event_btnSendMessageActionPerformed

    private void txtMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessageKeyPressed
        if (evt.getKeyCode() == 10) {
            //    sendMessage();
        }

        handleDefaultMessage();
    }//GEN-LAST:event_txtMessageKeyPressed

    private void txtMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMessageMouseClicked
        handleDefaultMessage();
    }//GEN-LAST:event_txtMessageMouseClicked

    private void txtMessageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMessageFocusLost

        String message = txtMessage.getText();

        if (message.equals("")) {
            resetTextMessage();
        }
    }//GEN-LAST:event_txtMessageFocusLost

    private void txtMessageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessageKeyReleased

    }//GEN-LAST:event_txtMessageKeyReleased

    private void handleDefaultMessage() {
        String message = txtMessage.getText();

        if (message.equals(DEFAULT_MESSAGE)) {
            txtMessage.setText("");
            txtMessage.setFont(new java.awt.Font("Open Sans", 0, 14));
            txtMessage.setForeground(Color.black);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authenticateWindow;
    private javax.swing.JButton btnAuthenticate;
    private javax.swing.JButton btnSendMessage;
    private javax.swing.JPanel buttonContainerPanel;
    private javax.swing.JPanel chatFormPanel;
    private javax.swing.JPanel chatMessagesItemsPanel;
    private javax.swing.JPanel chatMessagesPanel;
    private javax.swing.JScrollPane chatMessagesScrollPane;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JPanel chatWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane messageScrollPane;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JList userList;
    private javax.swing.JScrollPane userListScrollPane;
    private javax.swing.JPanel viewSwitcher;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (arg == null) {
            return;
        }

        if (o.getClass() == ChatClient.class) {
            ChatResponse response = (ChatResponse) arg;

            switch (response.getCommand()) {
                case "USERLIST":
                    int[] selectedIndicies = userList.getSelectedIndices();

                    DefaultListModel model = new DefaultListModel();
                    model.add(0, "Everyone");

                    String[] users = (String[]) response.getParameter("users");
                    for (int i = 0; i < users.length; i++) {
                        model.add(i + 1, users[i]);
                    }

                    userList.setModel(model);
                    userList.revalidate();
                    userList.repaint();

                    userList.setSelectedIndices(selectedIndicies);
                    break;
                case "MSG":
                    JPanel messageItem = new JPanel();
                    messageItem.setLayout(new FlowLayout(FlowLayout.LEFT));
                    JLabel lblUsername = new JLabel(((String) response.getParameter("sender")) + ":");
                    lblUsername.setFont(new java.awt.Font("Open Sans", 1, 13));
                    messageItem.add(lblUsername);

                    String message = (String) response.getParameter("message");
                    message = message.replaceAll("\n", "<br />");
                    JLabel lblMessage = new JLabel("<html>" + message);
                    messageItem.add(lblMessage);

                    chatMessagesItemsPanel.add(messageItem);

                    chatMessagesItemsPanel.revalidate();
                    chatMessagesItemsPanel.repaint();
                    break;
            }
        }
    }

    private void resetTextMessage() {
        txtMessage.setText(DEFAULT_MESSAGE);
        txtMessage.setFont(new Font("Open Sans", 1, 14));
        txtMessage.setForeground(Color.darkGray);
        txtMessage.requestFocus();
    }

    private void sendMessage() {
        String message = txtMessage.getText();

        if (message.equals("") || message.equals(DEFAULT_MESSAGE)) {
            return;
        }

        String receivers;
        List<String> selectedUsers = userList.getSelectedValuesList();
        if (selectedUsers.contains("Everyone")) {
            receivers = "*";
        } else {
            receivers = String.join(",", selectedUsers);
        }

        this.client.send("MSG#" + receivers + "#" + message);

        resetTextMessage();
    }
}
